from __future__ import annotations

from pathlib import Path

from src.shell.context.context import ShellContext


def _format_size(size: int, human: bool) -> str:
    if not human:
        return str(size)

    units = ("B", "K", "M", "G", "T", "P")
    value = float(size)

    for unit in units:
        if value < 1024 or unit == units[-1]:
            if unit == "B":
                return f"{int(value)} {unit}"
            return f"{value:.1f} {unit}"

        value /= 1024

    return f"{int(size)} B"


def _directory_size(
    path: Path,
    show_all: bool,
    output: list[str],
    human: bool,
) -> int:
    total = 0

    try:
        for entry in path.iterdir():
            try:
                if entry.is_symlink():
                    continue

                if entry.is_dir():
                    total += _directory_size(
                        entry,
                        show_all,
                        output,
                        human,
                    )
                elif entry.is_file():
                    size = entry.stat().st_size
                    total += size

                    if show_all:
                        output.append(
                            f"{_format_size(size, human):>10}  {entry}"
                        )

            except OSError:
                continue

    except OSError:
        return 0

    return total


def cmd_du(args: list[str], context: ShellContext) -> str:
    human = False
    show_all = False
    summarize = False
    paths: list[str] = []

    for arg in args:
        if arg == "--":
            continue

        if arg.startswith("-") and arg != "-":
            if arg.startswith("--"):
                flag = arg[2:]

                if flag == "human-readable":
                    human = True
                elif flag == "all":
                    show_all = True
                elif flag == "summarize":
                    summarize = True
                else:
                    return f"du: invalid option '--{flag}'\n"

                continue

            for flag in arg[1:]:
                if flag == "h":
                    human = True
                elif flag == "a":
                    show_all = True
                elif flag == "s":
                    summarize = True
                else:
                    return f"du: invalid option '-{flag}'\n"

            continue

        paths.append(arg)

    if not paths:
        paths = ["."]

    output: list[str] = []

    for arg in paths:
        target = context.resolve_path(arg)

        if not target.exists():
            output.append(
                f"du: cannot access '{arg}': File not found\n"
            )
            continue

        try:
            if target.is_file():
                size = target.stat().st_size

                if show_all or summarize:
                    output.append(
                        f"{_format_size(size, human):>10}  {arg}"
                    )
                else:
                    output.append(
                        f"{_format_size(size, human):>10}  {arg}"
                    )

                continue

            total = _directory_size(
                target,
                show_all,
                output,
                human,
            )

            # GNU du-style: directories are always printed.
            output.append(
                f"{_format_size(total, human):>10}  {arg}"
            )

        except OSError as exc:
            output.append(
                f"du: cannot access '{arg}': {exc}\n"
            )

    if summarize and len(paths) > 1:
        # Keep one summary per requested path.
        # File entries generated by -a are still valid.
        return "\n".join(output)

    return "\n".join(output)
